remote_theme: just-the-docs/just-the-docs

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme

# Optional but recommended
just_the_docs:
  logo: "/figures/logo.jpg"   # if you want a logo
  search_enabled: true

